### ISSUE TITLE
Module doesn't work for Prestashop 1.7.6.5

### ISSUE THREAD

**Issue by mehowbrains** [coinbase/coinbase-commerce-prestashop#18]
Hello,

I installed this module in my new prestashop 1.7.6.5 installation.

I tested with a client to make everything worked fine. He submitted and order, and the module received the status "Coinbase awaiting status". The payment went through on Coinbase Commerce side and went from "pending" to "completed".

But the payment completed was never reflected back to prestashop after it completed.  It still shows "Coinbase awaiting status" in the prestashop dashboard. It's not a big deal because in my Coinbase Commerce dashboard I get some meta data with the payment, so I can reference which completed payment is which order number -- but it would be nice for this to work properly. This is not a setting issue, but rather a module or server issue.

I believe that the second Coinbase commerce received the order, it should've had changed the message from "Coinbase awaiting status" to "Coinbase pending status" -- and then after some completed status from prestashop as the final status.

When I test my webhook connection by sending some test event, I get an HTTP 500 error. This module hasn't been updated in a long time, and I'm not sure if it's compatible with Prestashop 1.7.6.5.

What needs to be updated in the module for it to work again?

**Comment by oa-coinbase** [comment]
Hi @mehowbrains, unfortunately we will be deprecating this plugin/ repository at this moment. We may pick it back up down the line with updates, but for now feel free to fork it and apply any fixes for you/ the community. Thanks!
