### ISSUE TITLE
Error 500 when doing payment

### ISSUE THREAD

**Issue by nbexiga** [coinbase/coinbase-commerce-prestashop#2]
Hi
i have just installed the addon , but when submitting the purchase and go to the module payment option it appear error 500 on checkout . 
can you please help?
![errorbitcoin](https://user-images.githubusercontent.com/34128424/44785268-40734c00-ab88-11e8-951a-0bb5d42f06df.JPG)

**Comment by nbexiga** [comment]
In debug mode what is gives is this 
Parse error: syntax error, unexpected '?' in /home/pleasuresheaven.com/public_html/modules/coinbase/classes/OrderManager.php on line 18

**Comment by guacamoli** [comment]
Hey @nbexiga, this has been fixed in the latest code. Stay tuned for the latest release. Thanks for reporting.
