### ISSUE TITLE
API for prestashop 1.6

### ISSUE THREAD

**Issue by Edabea** [coinbase/coinbase-commerce-prestashop#3]
Hi!
I have a version prestashop 1.6 and the module is only valid as of version 1.7, is there any solution?
Regards.

**Comment by mickaelandrieu** [comment]
to be honest, I don't see anything specific to 1.7 release here...

How about updating the ps version compliancy to 1.6.1.? https://github.com/coinbase/coinbase-commerce-prestashop/blob/master/coinbase/coinbase.php#L21

**Comment by guacamoli** [comment]
Hey @Edabea, we've added support for 1.6 in the latest code. Stay tuned for the latest release.
