### ISSUE TITLE
Web hook validation fails

### ISSUE THREAD

**Issue by breandan81** [coinbase/coinbase-commerce-prestashop#4]
It's hashing with the API key.  It needs to be using the shared secret for the web hook.  I hardcoded mine for now but I'll try to modify the configuration form and update the validation method.  Is this being actively enough maintained that I can just do a pull request when it's done?  I've never done one before but it looks straightforward.

**Comment by breandan81** [comment]
I issued a pull requires for this let me know if this can be addressed.

**Comment by guacamoli** [comment]
Hey @breandan81, this has been fixed in the latest code. Stay tuned for the latest release.
